// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.20.3
// source: task.proto

package task

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ScraperTaskRoute_AddTask_FullMethodName    = "/ScraperTaskRoute/AddTask"
	ScraperTaskRoute_StopTask_FullMethodName   = "/ScraperTaskRoute/StopTask"
	ScraperTaskRoute_RunTask_FullMethodName    = "/ScraperTaskRoute/RunTask"
	ScraperTaskRoute_RemoveTask_FullMethodName = "/ScraperTaskRoute/RemoveTask"
	ScraperTaskRoute_UpdateTask_FullMethodName = "/ScraperTaskRoute/UpdateTask"
	ScraperTaskRoute_GetTask_FullMethodName    = "/ScraperTaskRoute/GetTask"
	ScraperTaskRoute_ListTasks_FullMethodName  = "/ScraperTaskRoute/ListTasks"
)

// ScraperTaskRouteClient is the client API for ScraperTaskRoute service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ScraperTaskRouteClient interface {
	AddTask(ctx context.Context, in *CreateTaskRequest, opts ...grpc.CallOption) (*Task, error)
	StopTask(ctx context.Context, in *TaskIdRequest, opts ...grpc.CallOption) (*TaskStatusResponse, error)
	RunTask(ctx context.Context, in *TaskIdRequest, opts ...grpc.CallOption) (*TaskStatusResponse, error)
	RemoveTask(ctx context.Context, in *TaskIdRequest, opts ...grpc.CallOption) (*RemovedTaskResponse, error)
	UpdateTask(ctx context.Context, in *UpdateTaskRequest, opts ...grpc.CallOption) (*Task, error)
	GetTask(ctx context.Context, in *TaskIdRequest, opts ...grpc.CallOption) (*Task, error)
	ListTasks(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*ListTasksResponse, error)
}

type scraperTaskRouteClient struct {
	cc grpc.ClientConnInterface
}

func NewScraperTaskRouteClient(cc grpc.ClientConnInterface) ScraperTaskRouteClient {
	return &scraperTaskRouteClient{cc}
}

func (c *scraperTaskRouteClient) AddTask(ctx context.Context, in *CreateTaskRequest, opts ...grpc.CallOption) (*Task, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Task)
	err := c.cc.Invoke(ctx, ScraperTaskRoute_AddTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scraperTaskRouteClient) StopTask(ctx context.Context, in *TaskIdRequest, opts ...grpc.CallOption) (*TaskStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskStatusResponse)
	err := c.cc.Invoke(ctx, ScraperTaskRoute_StopTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scraperTaskRouteClient) RunTask(ctx context.Context, in *TaskIdRequest, opts ...grpc.CallOption) (*TaskStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskStatusResponse)
	err := c.cc.Invoke(ctx, ScraperTaskRoute_RunTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scraperTaskRouteClient) RemoveTask(ctx context.Context, in *TaskIdRequest, opts ...grpc.CallOption) (*RemovedTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemovedTaskResponse)
	err := c.cc.Invoke(ctx, ScraperTaskRoute_RemoveTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scraperTaskRouteClient) UpdateTask(ctx context.Context, in *UpdateTaskRequest, opts ...grpc.CallOption) (*Task, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Task)
	err := c.cc.Invoke(ctx, ScraperTaskRoute_UpdateTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scraperTaskRouteClient) GetTask(ctx context.Context, in *TaskIdRequest, opts ...grpc.CallOption) (*Task, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Task)
	err := c.cc.Invoke(ctx, ScraperTaskRoute_GetTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scraperTaskRouteClient) ListTasks(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*ListTasksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTasksResponse)
	err := c.cc.Invoke(ctx, ScraperTaskRoute_ListTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ScraperTaskRouteServer is the server API for ScraperTaskRoute service.
// All implementations should embed UnimplementedScraperTaskRouteServer
// for forward compatibility.
type ScraperTaskRouteServer interface {
	AddTask(context.Context, *CreateTaskRequest) (*Task, error)
	StopTask(context.Context, *TaskIdRequest) (*TaskStatusResponse, error)
	RunTask(context.Context, *TaskIdRequest) (*TaskStatusResponse, error)
	RemoveTask(context.Context, *TaskIdRequest) (*RemovedTaskResponse, error)
	UpdateTask(context.Context, *UpdateTaskRequest) (*Task, error)
	GetTask(context.Context, *TaskIdRequest) (*Task, error)
	ListTasks(context.Context, *EmptyRequest) (*ListTasksResponse, error)
}

// UnimplementedScraperTaskRouteServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedScraperTaskRouteServer struct{}

func (UnimplementedScraperTaskRouteServer) AddTask(context.Context, *CreateTaskRequest) (*Task, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddTask not implemented")
}
func (UnimplementedScraperTaskRouteServer) StopTask(context.Context, *TaskIdRequest) (*TaskStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopTask not implemented")
}
func (UnimplementedScraperTaskRouteServer) RunTask(context.Context, *TaskIdRequest) (*TaskStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunTask not implemented")
}
func (UnimplementedScraperTaskRouteServer) RemoveTask(context.Context, *TaskIdRequest) (*RemovedTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveTask not implemented")
}
func (UnimplementedScraperTaskRouteServer) UpdateTask(context.Context, *UpdateTaskRequest) (*Task, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTask not implemented")
}
func (UnimplementedScraperTaskRouteServer) GetTask(context.Context, *TaskIdRequest) (*Task, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTask not implemented")
}
func (UnimplementedScraperTaskRouteServer) ListTasks(context.Context, *EmptyRequest) (*ListTasksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTasks not implemented")
}
func (UnimplementedScraperTaskRouteServer) testEmbeddedByValue() {}

// UnsafeScraperTaskRouteServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ScraperTaskRouteServer will
// result in compilation errors.
type UnsafeScraperTaskRouteServer interface {
	mustEmbedUnimplementedScraperTaskRouteServer()
}

func RegisterScraperTaskRouteServer(s grpc.ServiceRegistrar, srv ScraperTaskRouteServer) {
	// If the following call pancis, it indicates UnimplementedScraperTaskRouteServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ScraperTaskRoute_ServiceDesc, srv)
}

func _ScraperTaskRoute_AddTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScraperTaskRouteServer).AddTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScraperTaskRoute_AddTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScraperTaskRouteServer).AddTask(ctx, req.(*CreateTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScraperTaskRoute_StopTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScraperTaskRouteServer).StopTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScraperTaskRoute_StopTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScraperTaskRouteServer).StopTask(ctx, req.(*TaskIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScraperTaskRoute_RunTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScraperTaskRouteServer).RunTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScraperTaskRoute_RunTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScraperTaskRouteServer).RunTask(ctx, req.(*TaskIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScraperTaskRoute_RemoveTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScraperTaskRouteServer).RemoveTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScraperTaskRoute_RemoveTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScraperTaskRouteServer).RemoveTask(ctx, req.(*TaskIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScraperTaskRoute_UpdateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScraperTaskRouteServer).UpdateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScraperTaskRoute_UpdateTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScraperTaskRouteServer).UpdateTask(ctx, req.(*UpdateTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScraperTaskRoute_GetTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScraperTaskRouteServer).GetTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScraperTaskRoute_GetTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScraperTaskRouteServer).GetTask(ctx, req.(*TaskIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScraperTaskRoute_ListTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScraperTaskRouteServer).ListTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScraperTaskRoute_ListTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScraperTaskRouteServer).ListTasks(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ScraperTaskRoute_ServiceDesc is the grpc.ServiceDesc for ScraperTaskRoute service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ScraperTaskRoute_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ScraperTaskRoute",
	HandlerType: (*ScraperTaskRouteServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddTask",
			Handler:    _ScraperTaskRoute_AddTask_Handler,
		},
		{
			MethodName: "StopTask",
			Handler:    _ScraperTaskRoute_StopTask_Handler,
		},
		{
			MethodName: "RunTask",
			Handler:    _ScraperTaskRoute_RunTask_Handler,
		},
		{
			MethodName: "RemoveTask",
			Handler:    _ScraperTaskRoute_RemoveTask_Handler,
		},
		{
			MethodName: "UpdateTask",
			Handler:    _ScraperTaskRoute_UpdateTask_Handler,
		},
		{
			MethodName: "GetTask",
			Handler:    _ScraperTaskRoute_GetTask_Handler,
		},
		{
			MethodName: "ListTasks",
			Handler:    _ScraperTaskRoute_ListTasks_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "task.proto",
}
