// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.20.3
// source: task.proto

package task

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsRunning     bool                   `protobuf:"varint,1,opt,name=isRunning,proto3" json:"isRunning,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskStatusResponse) Reset() {
	*x = TaskStatusResponse{}
	mi := &file_task_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskStatusResponse) ProtoMessage() {}

func (x *TaskStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskStatusResponse.ProtoReflect.Descriptor instead.
func (*TaskStatusResponse) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{0}
}

func (x *TaskStatusResponse) GetIsRunning() bool {
	if x != nil {
		return x.IsRunning
	}
	return false
}

type RemovedTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsTaskRemoved bool                   `protobuf:"varint,1,opt,name=isTaskRemoved,proto3" json:"isTaskRemoved,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemovedTaskResponse) Reset() {
	*x = RemovedTaskResponse{}
	mi := &file_task_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemovedTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemovedTaskResponse) ProtoMessage() {}

func (x *RemovedTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemovedTaskResponse.ProtoReflect.Descriptor instead.
func (*RemovedTaskResponse) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{1}
}

func (x *RemovedTaskResponse) GetIsTaskRemoved() bool {
	if x != nil {
		return x.IsTaskRemoved
	}
	return false
}

type CreateTaskRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DelayInSeconds uint32                 `protobuf:"varint,1,opt,name=delayInSeconds,proto3" json:"delayInSeconds,omitempty"`
	SearchKeyword  string                 `protobuf:"bytes,2,opt,name=searchKeyword,proto3" json:"searchKeyword,omitempty"`
	LocationId     string                 `protobuf:"bytes,3,opt,name=locationId,proto3" json:"locationId,omitempty"`
	TaskType       string                 `protobuf:"bytes,4,opt,name=taskType,proto3" json:"taskType,omitempty"`
	DistanceRadius string                 `protobuf:"bytes,5,opt,name=distanceRadius,proto3" json:"distanceRadius,omitempty"`
	TaskLocation   string                 `protobuf:"bytes,6,opt,name=taskLocation,proto3" json:"taskLocation,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateTaskRequest) Reset() {
	*x = CreateTaskRequest{}
	mi := &file_task_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskRequest) ProtoMessage() {}

func (x *CreateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateTaskRequest) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTaskRequest) GetDelayInSeconds() uint32 {
	if x != nil {
		return x.DelayInSeconds
	}
	return 0
}

func (x *CreateTaskRequest) GetSearchKeyword() string {
	if x != nil {
		return x.SearchKeyword
	}
	return ""
}

func (x *CreateTaskRequest) GetLocationId() string {
	if x != nil {
		return x.LocationId
	}
	return ""
}

func (x *CreateTaskRequest) GetTaskType() string {
	if x != nil {
		return x.TaskType
	}
	return ""
}

func (x *CreateTaskRequest) GetDistanceRadius() string {
	if x != nil {
		return x.DistanceRadius
	}
	return ""
}

func (x *CreateTaskRequest) GetTaskLocation() string {
	if x != nil {
		return x.TaskLocation
	}
	return ""
}

type TaskIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=taskId,proto3" json:"taskId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskIdRequest) Reset() {
	*x = TaskIdRequest{}
	mi := &file_task_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskIdRequest) ProtoMessage() {}

func (x *TaskIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskIdRequest.ProtoReflect.Descriptor instead.
func (*TaskIdRequest) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{3}
}

func (x *TaskIdRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type UpdateTaskRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TaskId         *TaskIdRequest         `protobuf:"bytes,1,opt,name=taskId,proto3" json:"taskId,omitempty"`
	DelayInSeconds uint32                 `protobuf:"varint,2,opt,name=delayInSeconds,proto3" json:"delayInSeconds,omitempty"`
	SearchKeyword  string                 `protobuf:"bytes,3,opt,name=searchKeyword,proto3" json:"searchKeyword,omitempty"`
	LocationId     string                 `protobuf:"bytes,4,opt,name=locationId,proto3" json:"locationId,omitempty"`
	DistanceRadius string                 `protobuf:"bytes,5,opt,name=distanceRadius,proto3" json:"distanceRadius,omitempty"`
	TaskLocation   string                 `protobuf:"bytes,6,opt,name=taskLocation,proto3" json:"taskLocation,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateTaskRequest) Reset() {
	*x = UpdateTaskRequest{}
	mi := &file_task_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskRequest) ProtoMessage() {}

func (x *UpdateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskRequest.ProtoReflect.Descriptor instead.
func (*UpdateTaskRequest) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateTaskRequest) GetTaskId() *TaskIdRequest {
	if x != nil {
		return x.TaskId
	}
	return nil
}

func (x *UpdateTaskRequest) GetDelayInSeconds() uint32 {
	if x != nil {
		return x.DelayInSeconds
	}
	return 0
}

func (x *UpdateTaskRequest) GetSearchKeyword() string {
	if x != nil {
		return x.SearchKeyword
	}
	return ""
}

func (x *UpdateTaskRequest) GetLocationId() string {
	if x != nil {
		return x.LocationId
	}
	return ""
}

func (x *UpdateTaskRequest) GetDistanceRadius() string {
	if x != nil {
		return x.DistanceRadius
	}
	return ""
}

func (x *UpdateTaskRequest) GetTaskLocation() string {
	if x != nil {
		return x.TaskLocation
	}
	return ""
}

type Task struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TaskId         string                 `protobuf:"bytes,1,opt,name=taskId,proto3" json:"taskId,omitempty"`
	TaskType       string                 `protobuf:"bytes,2,opt,name=taskType,proto3" json:"taskType,omitempty"`
	DelayInSeconds uint32                 `protobuf:"varint,3,opt,name=delayInSeconds,proto3" json:"delayInSeconds,omitempty"`
	SearchKeyword  string                 `protobuf:"bytes,4,opt,name=searchKeyword,proto3" json:"searchKeyword,omitempty"`
	LocationId     string                 `protobuf:"bytes,5,opt,name=locationId,proto3" json:"locationId,omitempty"`
	DistanceRadius string                 `protobuf:"bytes,6,opt,name=distanceRadius,proto3" json:"distanceRadius,omitempty"`
	TaskLocation   string                 `protobuf:"bytes,7,opt,name=taskLocation,proto3" json:"taskLocation,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,8,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt      string                 `protobuf:"bytes,9,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_task_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{5}
}

func (x *Task) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *Task) GetTaskType() string {
	if x != nil {
		return x.TaskType
	}
	return ""
}

func (x *Task) GetDelayInSeconds() uint32 {
	if x != nil {
		return x.DelayInSeconds
	}
	return 0
}

func (x *Task) GetSearchKeyword() string {
	if x != nil {
		return x.SearchKeyword
	}
	return ""
}

func (x *Task) GetLocationId() string {
	if x != nil {
		return x.LocationId
	}
	return ""
}

func (x *Task) GetDistanceRadius() string {
	if x != nil {
		return x.DistanceRadius
	}
	return ""
}

func (x *Task) GetTaskLocation() string {
	if x != nil {
		return x.TaskLocation
	}
	return ""
}

func (x *Task) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Task) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type ListTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*Task                `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksResponse) Reset() {
	*x = ListTasksResponse{}
	mi := &file_task_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksResponse) ProtoMessage() {}

func (x *ListTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksResponse.ProtoReflect.Descriptor instead.
func (*ListTasksResponse) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{6}
}

func (x *ListTasksResponse) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type EmptyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyRequest) Reset() {
	*x = EmptyRequest{}
	mi := &file_task_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyRequest) ProtoMessage() {}

func (x *EmptyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyRequest.ProtoReflect.Descriptor instead.
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{7}
}

var File_task_proto protoreflect.FileDescriptor

const file_task_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"task.proto\"2\n" +
	"\x12TaskStatusResponse\x12\x1c\n" +
	"\tisRunning\x18\x01 \x01(\bR\tisRunning\";\n" +
	"\x13RemovedTaskResponse\x12$\n" +
	"\risTaskRemoved\x18\x01 \x01(\bR\risTaskRemoved\"\xe9\x01\n" +
	"\x11CreateTaskRequest\x12&\n" +
	"\x0edelayInSeconds\x18\x01 \x01(\rR\x0edelayInSeconds\x12$\n" +
	"\rsearchKeyword\x18\x02 \x01(\tR\rsearchKeyword\x12\x1e\n" +
	"\n" +
	"locationId\x18\x03 \x01(\tR\n" +
	"locationId\x12\x1a\n" +
	"\btaskType\x18\x04 \x01(\tR\btaskType\x12&\n" +
	"\x0edistanceRadius\x18\x05 \x01(\tR\x0edistanceRadius\x12\"\n" +
	"\ftaskLocation\x18\x06 \x01(\tR\ftaskLocation\"'\n" +
	"\rTaskIdRequest\x12\x16\n" +
	"\x06taskId\x18\x01 \x01(\tR\x06taskId\"\xf5\x01\n" +
	"\x11UpdateTaskRequest\x12&\n" +
	"\x06taskId\x18\x01 \x01(\v2\x0e.TaskIdRequestR\x06taskId\x12&\n" +
	"\x0edelayInSeconds\x18\x02 \x01(\rR\x0edelayInSeconds\x12$\n" +
	"\rsearchKeyword\x18\x03 \x01(\tR\rsearchKeyword\x12\x1e\n" +
	"\n" +
	"locationId\x18\x04 \x01(\tR\n" +
	"locationId\x12&\n" +
	"\x0edistanceRadius\x18\x05 \x01(\tR\x0edistanceRadius\x12\"\n" +
	"\ftaskLocation\x18\x06 \x01(\tR\ftaskLocation\"\xb0\x02\n" +
	"\x04Task\x12\x16\n" +
	"\x06taskId\x18\x01 \x01(\tR\x06taskId\x12\x1a\n" +
	"\btaskType\x18\x02 \x01(\tR\btaskType\x12&\n" +
	"\x0edelayInSeconds\x18\x03 \x01(\rR\x0edelayInSeconds\x12$\n" +
	"\rsearchKeyword\x18\x04 \x01(\tR\rsearchKeyword\x12\x1e\n" +
	"\n" +
	"locationId\x18\x05 \x01(\tR\n" +
	"locationId\x12&\n" +
	"\x0edistanceRadius\x18\x06 \x01(\tR\x0edistanceRadius\x12\"\n" +
	"\ftaskLocation\x18\a \x01(\tR\ftaskLocation\x12\x1c\n" +
	"\tcreatedAt\x18\b \x01(\tR\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\t \x01(\tR\tupdatedAt\"0\n" +
	"\x11ListTasksResponse\x12\x1b\n" +
	"\x05tasks\x18\x01 \x03(\v2\x05.TaskR\x05tasks\"\x0e\n" +
	"\fEmptyRequest2\xd6\x02\n" +
	"\x10ScraperTaskRoute\x12&\n" +
	"\aAddTask\x12\x12.CreateTaskRequest\x1a\x05.Task\"\x00\x121\n" +
	"\bStopTask\x12\x0e.TaskIdRequest\x1a\x13.TaskStatusResponse\"\x00\x120\n" +
	"\aRunTask\x12\x0e.TaskIdRequest\x1a\x13.TaskStatusResponse\"\x00\x124\n" +
	"\n" +
	"RemoveTask\x12\x0e.TaskIdRequest\x1a\x14.RemovedTaskResponse\"\x00\x12)\n" +
	"\n" +
	"UpdateTask\x12\x12.UpdateTaskRequest\x1a\x05.Task\"\x00\x12\"\n" +
	"\aGetTask\x12\x0e.TaskIdRequest\x1a\x05.Task\"\x00\x120\n" +
	"\tListTasks\x12\r.EmptyRequest\x1a\x12.ListTasksResponse\"\x00B8Z6github.com/usmanfarooq1/job-radar/internal/common/taskb\x06proto3"

var (
	file_task_proto_rawDescOnce sync.Once
	file_task_proto_rawDescData []byte
)

func file_task_proto_rawDescGZIP() []byte {
	file_task_proto_rawDescOnce.Do(func() {
		file_task_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_task_proto_rawDesc), len(file_task_proto_rawDesc)))
	})
	return file_task_proto_rawDescData
}

var file_task_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_task_proto_goTypes = []any{
	(*TaskStatusResponse)(nil),  // 0: TaskStatusResponse
	(*RemovedTaskResponse)(nil), // 1: RemovedTaskResponse
	(*CreateTaskRequest)(nil),   // 2: CreateTaskRequest
	(*TaskIdRequest)(nil),       // 3: TaskIdRequest
	(*UpdateTaskRequest)(nil),   // 4: UpdateTaskRequest
	(*Task)(nil),                // 5: Task
	(*ListTasksResponse)(nil),   // 6: ListTasksResponse
	(*EmptyRequest)(nil),        // 7: EmptyRequest
}
var file_task_proto_depIdxs = []int32{
	3, // 0: UpdateTaskRequest.taskId:type_name -> TaskIdRequest
	5, // 1: ListTasksResponse.tasks:type_name -> Task
	2, // 2: ScraperTaskRoute.AddTask:input_type -> CreateTaskRequest
	3, // 3: ScraperTaskRoute.StopTask:input_type -> TaskIdRequest
	3, // 4: ScraperTaskRoute.RunTask:input_type -> TaskIdRequest
	3, // 5: ScraperTaskRoute.RemoveTask:input_type -> TaskIdRequest
	4, // 6: ScraperTaskRoute.UpdateTask:input_type -> UpdateTaskRequest
	3, // 7: ScraperTaskRoute.GetTask:input_type -> TaskIdRequest
	7, // 8: ScraperTaskRoute.ListTasks:input_type -> EmptyRequest
	5, // 9: ScraperTaskRoute.AddTask:output_type -> Task
	0, // 10: ScraperTaskRoute.StopTask:output_type -> TaskStatusResponse
	0, // 11: ScraperTaskRoute.RunTask:output_type -> TaskStatusResponse
	1, // 12: ScraperTaskRoute.RemoveTask:output_type -> RemovedTaskResponse
	5, // 13: ScraperTaskRoute.UpdateTask:output_type -> Task
	5, // 14: ScraperTaskRoute.GetTask:output_type -> Task
	6, // 15: ScraperTaskRoute.ListTasks:output_type -> ListTasksResponse
	9, // [9:16] is the sub-list for method output_type
	2, // [2:9] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_task_proto_init() }
func file_task_proto_init() {
	if File_task_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_task_proto_rawDesc), len(file_task_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_task_proto_goTypes,
		DependencyIndexes: file_task_proto_depIdxs,
		MessageInfos:      file_task_proto_msgTypes,
	}.Build()
	File_task_proto = out.File
	file_task_proto_goTypes = nil
	file_task_proto_depIdxs = nil
}
