// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type JobApplicationStatusEnum string

const (
	JobApplicationStatusEnumBookmarked   JobApplicationStatusEnum = "bookmarked"
	JobApplicationStatusEnumApplied      JobApplicationStatusEnum = "applied"
	JobApplicationStatusEnumInterviewing JobApplicationStatusEnum = "interviewing"
	JobApplicationStatusEnumRejected     JobApplicationStatusEnum = "rejected"
	JobApplicationStatusEnumNegotiating  JobApplicationStatusEnum = "negotiating"
	JobApplicationStatusEnumAccepted     JobApplicationStatusEnum = "accepted"
)

func (e *JobApplicationStatusEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = JobApplicationStatusEnum(s)
	case string:
		*e = JobApplicationStatusEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for JobApplicationStatusEnum: %T", src)
	}
	return nil
}

type NullJobApplicationStatusEnum struct {
	JobApplicationStatusEnum JobApplicationStatusEnum
	Valid                    bool // Valid is true if JobApplicationStatusEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullJobApplicationStatusEnum) Scan(value interface{}) error {
	if value == nil {
		ns.JobApplicationStatusEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.JobApplicationStatusEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullJobApplicationStatusEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.JobApplicationStatusEnum), nil
}

type JobApplyTypeEnum string

const (
	JobApplyTypeEnumEasyApply JobApplyTypeEnum = "easy_apply"
	JobApplyTypeEnumApply     JobApplyTypeEnum = "apply"
)

func (e *JobApplyTypeEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = JobApplyTypeEnum(s)
	case string:
		*e = JobApplyTypeEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for JobApplyTypeEnum: %T", src)
	}
	return nil
}

type NullJobApplyTypeEnum struct {
	JobApplyTypeEnum JobApplyTypeEnum
	Valid            bool // Valid is true if JobApplyTypeEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullJobApplyTypeEnum) Scan(value interface{}) error {
	if value == nil {
		ns.JobApplyTypeEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.JobApplyTypeEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullJobApplyTypeEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.JobApplyTypeEnum), nil
}

type SkillTypeEnum string

const (
	SkillTypeEnumBackend    SkillTypeEnum = "backend"
	SkillTypeEnumFrontend   SkillTypeEnum = "frontend"
	SkillTypeEnumOperations SkillTypeEnum = "operations"
	SkillTypeEnumDeployment SkillTypeEnum = "deployment"
	SkillTypeEnumTools      SkillTypeEnum = "tools"
)

func (e *SkillTypeEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SkillTypeEnum(s)
	case string:
		*e = SkillTypeEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for SkillTypeEnum: %T", src)
	}
	return nil
}

type NullSkillTypeEnum struct {
	SkillTypeEnum SkillTypeEnum
	Valid         bool // Valid is true if SkillTypeEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSkillTypeEnum) Scan(value interface{}) error {
	if value == nil {
		ns.SkillTypeEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SkillTypeEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSkillTypeEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SkillTypeEnum), nil
}

type TaskStateEnum string

const (
	TaskStateEnumRunning TaskStateEnum = "running"
	TaskStateEnumPaused  TaskStateEnum = "paused"
)

func (e *TaskStateEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TaskStateEnum(s)
	case string:
		*e = TaskStateEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for TaskStateEnum: %T", src)
	}
	return nil
}

type NullTaskStateEnum struct {
	TaskStateEnum TaskStateEnum
	Valid         bool // Valid is true if TaskStateEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTaskStateEnum) Scan(value interface{}) error {
	if value == nil {
		ns.TaskStateEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TaskStateEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTaskStateEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TaskStateEnum), nil
}

type TaskTypeEnum string

const (
	TaskTypeEnumLinkedin TaskTypeEnum = "linkedin"
)

func (e *TaskTypeEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TaskTypeEnum(s)
	case string:
		*e = TaskTypeEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for TaskTypeEnum: %T", src)
	}
	return nil
}

type NullTaskTypeEnum struct {
	TaskTypeEnum TaskTypeEnum
	Valid        bool // Valid is true if TaskTypeEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTaskTypeEnum) Scan(value interface{}) error {
	if value == nil {
		ns.TaskTypeEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TaskTypeEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTaskTypeEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TaskTypeEnum), nil
}

type Job struct {
	JobID                uuid.UUID
	Title                string
	Company              string
	DescriptionText      string
	DescriptionTextHash  string
	HiringManagerName    pgtype.Text
	JobLocation          pgtype.Text
	LocationID           string
	DelayInSeconds       int32
	JobApplicationStatus JobApplicationStatusEnum
	MatchPercentages     []byte
	JobApplyType         JobApplyTypeEnum
	JobLink              string
	Notes                pgtype.Text
	CreatedAt            time.Time
	AppliedAt            time.Time
}

type Skill struct {
	SkillID   uuid.UUID
	SkillName string
	SkillType SkillTypeEnum
	CreatedAt time.Time
}

type Task struct {
	TaskID         uuid.UUID
	SearchLocation string
	LocationID     string
	DelayInSeconds uint32
	TaskState      TaskStateEnum
	TaskType       TaskTypeEnum
	SearchKeyword  string
	DistanceRadius uint8
	CreatedAt      time.Time
	UpdatedAt      time.Time
}
