// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: task.query.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks(task_id, search_location,location_id,delay_in_seconds,task_state,task_type,search_keyword,distance_radius,created_at,updated_at)
 VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)
RETURNING task_id, search_location, location_id, delay_in_seconds, task_state, task_type, search_keyword, distance_radius, created_at, updated_at
`

type CreateTaskParams struct {
	TaskID         uuid.UUID
	SearchLocation string
	LocationID     string
	DelayInSeconds uint32
	TaskState      TaskStateEnum
	TaskType       TaskTypeEnum
	SearchKeyword  string
	DistanceRadius uint8
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.TaskID,
		arg.SearchLocation,
		arg.LocationID,
		arg.DelayInSeconds,
		arg.TaskState,
		arg.TaskType,
		arg.SearchKeyword,
		arg.DistanceRadius,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Task
	err := row.Scan(
		&i.TaskID,
		&i.SearchLocation,
		&i.LocationID,
		&i.DelayInSeconds,
		&i.TaskState,
		&i.TaskType,
		&i.SearchKeyword,
		&i.DistanceRadius,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks
WHERE task_id = $1
`

func (q *Queries) DeleteTask(ctx context.Context, taskID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTask, taskID)
	return err
}

const getTask = `-- name: GetTask :one
SELECT task_id, search_location, location_id, delay_in_seconds, task_state, task_type, search_keyword, distance_radius, created_at, updated_at FROM tasks
WHERE task_id = $1 LIMIT 1
`

func (q *Queries) GetTask(ctx context.Context, taskID uuid.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, getTask, taskID)
	var i Task
	err := row.Scan(
		&i.TaskID,
		&i.SearchLocation,
		&i.LocationID,
		&i.DelayInSeconds,
		&i.TaskState,
		&i.TaskType,
		&i.SearchKeyword,
		&i.DistanceRadius,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTasks = `-- name: ListTasks :many
SELECT task_id, search_location, location_id, delay_in_seconds, task_state, task_type, search_keyword, distance_radius, created_at, updated_at FROM tasks
ORDER BY search_location
`

func (q *Queries) ListTasks(ctx context.Context) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.TaskID,
			&i.SearchLocation,
			&i.LocationID,
			&i.DelayInSeconds,
			&i.TaskState,
			&i.TaskType,
			&i.SearchKeyword,
			&i.DistanceRadius,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTask = `-- name: UpdateTask :exec
UPDATE tasks SET search_location = $1,location_id = $2,delay_in_seconds = $3,task_state = $4,search_keyword = $5,distance_radius = $6,updated_at = $7 WHERE task_id = $8
RETURNING task_id, search_location, location_id, delay_in_seconds, task_state, task_type, search_keyword, distance_radius, created_at, updated_at
`

type UpdateTaskParams struct {
	SearchLocation string
	LocationID     string
	DelayInSeconds uint32
	TaskState      TaskStateEnum
	SearchKeyword  string
	DistanceRadius uint8
	UpdatedAt      time.Time
	TaskID         uuid.UUID
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) error {
	_, err := q.db.Exec(ctx, updateTask,
		arg.SearchLocation,
		arg.LocationID,
		arg.DelayInSeconds,
		arg.TaskState,
		arg.SearchKeyword,
		arg.DistanceRadius,
		arg.UpdatedAt,
		arg.TaskID,
	)
	return err
}
